### ISSUE TITLE
Bing in web client cannot understand the context

### ISSUE THREAD

**Issue by TNTcraftHIM** [waylaidwanderer/chatgpt-web-client#6]
When using web client with ChatGPT, it works perfectly fine, but when using the client with Bing, it seems like Bing AI couldn't understand the context and treating each question seperately (see screenshots blow)

![screenshot](https://user-images.githubusercontent.com/35992542/223783355-e2a83ed1-c57b-459f-a344-9f0b081a9576.png)

**Comment by TNTcraftHIM** [comment]
Just found out where the problem is, I noticed that there is an if checking whether the response has "conversationSignature" and has no "messageId" at the same time, but when in Bing mode, the backend api will return a messageId, so we cannot add conversationSignature to the new line of conversation, therefore the context is lost

I temporarily fixed it by removing the "&& !result.messageId" part, please check if there's any other better solution to this if possible, thanks!

![screenshot](https://user-images.githubusercontent.com/35992542/223787633-1514d234-e38c-4b61-98b4-d2548302cc6f.png)

**Comment by waylaidwanderer** [comment]
@TNTcraftHIM The web client only supports the latest version of my client, so you'll need to update it.

**Comment by TNTcraftHIM** [comment]
Yes I am using latest web client and node-chatgpt-api from your repo, but the problem persist, please try using web client on your backend with Bing model selected

**Comment by waylaidwanderer** [comment]
@TNTcraftHIM oh yes, you're right. I misunderstood what you were saying.

**Comment by waylaidwanderer** [comment]
@TNTcraftHIM your solution was the correct one, I believe. I've pushed a change for this.

**Comment by TNTcraftHIM** [comment]
Thanks for your patience! BTW could you add a tick box or an option in .env file so that we could set the "jailbreakConversationId" to "true" if we need to use sydney? I've made some changes to the node-chatgpt-api so it supports the sydney client in the settings, I'll make a pr later about it

**Comment by waylaidwanderer** [comment]
I'm working on a way to set that in the browser (by adding a settings modal).

**Comment by TNTcraftHIM** [comment]
Thank you very much for your time! I like this project very much since Sydney is way much better than the one that Bing is using now
